import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {FILES,newer,sha256,validateManifest,applyFiles,rollbackFiles} from '../src/updater.mjs';
function manifest(){return {schema:1,version:'0.3.0',files:FILES.map((file,i)=>({path:file,asset:`media-${i}.bin`,size:3,sha256:sha256(Buffer.from('new'))}))};}
test('更新版本与清单拒绝降级判断、路径穿越及重复文件',()=>{assert.equal(newer('0.10.0','0.9.0'),true);assert.equal(newer('0.3.0','0.3.0'),false);assert.equal(newer('0.2.0','0.3.0'),false);assert.throws(()=>newer('rc','0.3.0'));validateManifest(manifest());const m=manifest();m.files[0].path='../数据/settings.json';assert.throws(()=>validateManifest(m));const n=manifest();n.files[1]=n.files[0];assert.throws(()=>validateManifest(n));});
test('中文空格目录按校验替换、保留账号配置下载文件、可回滚',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'媒体 更新-'));try{const directory=path.join(root,'.media-update','sample'),m=manifest(),f=m.files[0];await fs.mkdir(path.join(directory,'staged'),{recursive:true});await fs.mkdir(path.join(root,'数据'));await fs.mkdir(path.join(root,'下载结果'));await fs.writeFile(path.join(root,f.path),'old');await fs.writeFile(path.join(root,'数据/settings.json'),'settings');await fs.writeFile(path.join(root,'数据/session'),'cookie');await fs.writeFile(path.join(root,'下载结果/image.webp'),'image');await fs.writeFile(path.join(directory,'staged',f.path),'bad');await assert.rejects(applyFiles(root,directory,m,[f]),/校验/);assert.equal(await fs.readFile(path.join(root,f.path),'utf8'),'old');await fs.writeFile(path.join(directory,'staged',f.path),'new');const installed=await applyFiles(root,directory,m,[f]);assert.equal(await fs.readFile(path.join(root,f.path),'utf8'),'new');assert.equal(await fs.readFile(path.join(root,'数据/session'),'utf8'),'cookie');assert.equal(await fs.readFile(path.join(root,'数据/settings.json'),'utf8'),'settings');assert.equal(await fs.readFile(path.join(root,'下载结果/image.webp'),'utf8'),'image');await rollbackFiles(installed);assert.equal(await fs.readFile(path.join(root,f.path),'utf8'),'old');}finally{await fs.rm(root,{recursive:true,force:true});}});
